# NumPy

NumPy is an open-source library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Mathematical operations on NumPy's `ndarray` objects are up to 50x faster than iterating over native Python lists using loops.

It contains built-in functions that improve quality of life when working with arrays and math, such as functions for linear algebra, array transformations, and matrix manipulation.

It requires fewer lines of code for most mathematical operations than native Python `list`.

- The NumPy array - an n-dimensional data structure (`ndarray`) - is the central object of the NumPy package.

- A one-dimensional NumPy array can be thought of as a vector, a two-dimensional array as a matrix (i.e., a set of vectors), and a three-dimensional array as a tensor (i.e., a set of matrices).

- Within an array, the data type must be consistent (e.g., all integers or all floats).

## Defining arrays

### The `np.array()` function

In [1]:
import numpy as np    # common convention to alias numpy as np

To define a 1D array, pass a list to the `np.array()` function. This creates a one dimensional array (also called a vector)

In [2]:
x = np.array([1, 2, 3])    # number of dimensions of the array is 1

In [3]:
x

array([1, 2, 3])

In [4]:
# checking the dimension
x.shape    # the output of the shape attribute is a tuple

(3,)

To create a 2D arary, pass multiple lists inside an outer list:

In [5]:
# defining a 2D array, each dimension is of size 3
# in other words, this is a 3by3 matrix
y = np.array([
    [1, 2, 3],
    [11, 12, 13],
    [21, 22, 23]
])

In [6]:
y

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [7]:
y.shape    # notice that the output now contains two elements inside the tuple

(3, 3)

### The `np.arange()` function

This function behaves much like Python's built-in `range()` function. It returns a 1D array

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,5)

array([1, 2, 3, 4])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### `np.zeros()`, `np.ones()`, `np.full()` functions

In [11]:
# passing 5 as the shape of the array
np.zeros(5)    # returns a 1D array with 5 elements, all zeroes

array([0., 0., 0., 0., 0.])

In [12]:
# passing a list as the shape of the array
np.zeros([3, 2])    # returns a 3by2 matrix of all zeroes

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
# passing a tuple as the shape of the array
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
# we can also pass the shape of some other array:
np.ones(shape = y.shape)    # y was defined earlier, it's a 3by3 matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# creating a 1D array with all tens
np.full(shape = 4, fill_value = 10)

array([10, 10, 10, 10])

In [17]:
# creating a matrix of all fives
np.full(shape = [2, 3], fill_value = 5)

array([[5, 5, 5],
       [5, 5, 5]])

### `np.zeros_like()`, `np.ones_like()`, `np.full_like()` functions

These functions are used to create arrays that resemble the shape of some other array

In [18]:
# x was defined to be a 1D array with three elements
np.zeros_like(x)

array([0, 0, 0])

In [19]:
np.ones_like(y)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
# y was defined earlier, it's a 3by3 matrix
np.full_like(y, 5)    # fill each value with 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### Creating identity matrix

#### `np.identity()` function

In [21]:
np.identity(n = 2)    # n is the number of rows and columns, since square matrix

array([[1., 0.],
       [0., 1.]])

#### `np.eye()` function

This one is more flexible. Examples below:

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(N = 2, M = 3)    # N = rows, M = columns, M is optional argument

array([[1., 0., 0.],
       [0., 1., 0.]])

In [24]:
# k = 0 is the default
np.eye(N = 4, M = 5, k = 0)    # when k is 0, the ones are on the main diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [25]:
np.eye(N = 4, M = 5, k = 1)    # k = 1 means the first upper diagonal, and so on

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.eye(N = 4, M = 5, k = 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.eye(N = 4, M = 5, k = 3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.eye(N = 4, M = 5, k = -1)    # k = -1 means the first lower diagonal

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [29]:
np.eye(N = 4, M = 5, k = -2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

## Data type

By default numpy array values are stored as `float64` (64 bit floating point numbers). However, when we know that we need to store only integers, then creating `float64` arrays is a waste of computer memory.

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Array shape
We have already seen how to inspect the size or dimension of an array using the `.shape` attribute:

In [32]:
x

array([1, 2, 3])

In [33]:
x.shape

(3,)

In [34]:
y

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [35]:
y.shape

(3, 3)

### Reshaping arrays

In [36]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
a.reshape((2, 5))    # two rows, three columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [38]:
# we can put -1 to let python calculate the appropriate size of a dimension
a.reshape(2, -1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
b = a.reshape(-1, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
x    # one dimensional arraye

array([1, 2, 3])

In [41]:
xtwo = x.reshape((1, 3))    # this is actually two dimensional
xtwo

array([[1, 2, 3]])

In [42]:
xtwo.shape

(1, 3)

In [43]:
x.reshape((3, 1))    # this is also two dimensional

array([[1],
       [2],
       [3]])

### Transpose

In [44]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
b.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [46]:
y.transpose()

array([[ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23]])

## Arithmetic with NumPy Arrays

We can use python operators like +, - etc on arrays. The operands can be two arrays, or one array and one scalar.

### Arithmetic with scalars

When performing arithmetic between an array and a scalar, the scalar value gets broadcasted or propagated to each element in the array:

In [47]:
x

array([1, 2, 3])

In [48]:
x + 5

array([6, 7, 8])

In [49]:
x**2

array([1, 4, 9])

### Arithmetic between arrays

#### When same dimension

In [50]:
z = np.arange(1, 10).reshape((3, 3))
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
y + z    # since shape is the same, it performs element-wise addition

array([[ 2,  4,  6],
       [15, 17, 19],
       [28, 30, 32]])

#### When dimension is not the same

In [52]:
y

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [53]:
x

array([1, 2, 3])

In [54]:
# here, x gets broadcast to each row of y
y + x

array([[ 2,  4,  6],
       [12, 14, 16],
       [22, 24, 26]])

In [55]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [56]:
# here, the reshaped x (a column matrix) gets propagated to each column of y
y + x.reshape((3, 1))

array([[ 2,  3,  4],
       [13, 14, 15],
       [24, 25, 26]])

## Indexing and slicing

Used to select/extract a subset a of values from an array. The rules and syntax for indexing are similar to that of list/string.

- Indexing starts from 0 as usual
- Commas separate axes of an array
- Colons mean "through". For example, x[0:5] means the first 5 rows (rows 0 through 4) of x
- Negative numbers mean "from the end of the array." For example, x[-1] means the last row of x
- Blanks before or after colons means "the rest of". For example, x[3:] means the rest of the rows in x starting from row 3. Similarly, x[:3] means all the rows before row 3. x[:] means all rows of x
- When there are fewer indices than axes, the missing indices are considered complete slices. For example, in a 3-axis array, x[0,0] means all data in the 3rd axis of the 1st row and 1st column

In [57]:
u = np.arange(1, 101).reshape((10, 10))
u

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [58]:
u[1]    # second row

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
u[1, :]    # second row, same as above

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [60]:
u[:, 2]    # all values of third column

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [61]:
u[-1]    # last row

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [62]:
u[:5, :5]    # upper left quadrant

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [63]:
u[4:, 4:]    # lower right corner quadrant

array([[ 45,  46,  47,  48,  49,  50],
       [ 55,  56,  57,  58,  59,  60],
       [ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [64]:
u[0:10:2]    # first through last row skipping every 2nd row

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [65]:
u[0:10:2, 0:10:2]    # same as above, but also for columns

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])

## Basic matrix and linear algebra operations

### Matrix multiplication (`np.matmul()` function)

#### Multiplying two matrices

The output is a two dimensional array (matrix)

In [66]:
y    # y is a 3by3 matrix

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [67]:
z = np.arange(1, 7).reshape((3, 2))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
np.matmul(y, z)

array([[ 22,  28],
       [112, 148],
       [202, 268]])

In [69]:
np.matmul(z.transpose(), y)

array([[139, 148, 157],
       [172, 184, 196]])

#### Multiplying a matrix with a vector and vice-vers

The output is a 1D array (vector)

In [70]:
x    # x is one dimensional, has 3 elements

array([1, 2, 3])

In [71]:
y    # y is a 3by3 matrix

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [72]:
np.matmul(x, y)    # here, x acts like a 1by3 matrix

array([86, 92, 98])

In [73]:
np.matmul(y, x)    # here, x acts like a 3by1 matrix

array([ 14,  74, 134])

### Trace of a mtrix

In [74]:
y.trace()    # sum of the diagonal elements

np.int64(36)

### Rank of a matrix

In [75]:
np.linalg.matrix_rank(y)    # the matrix y is of rank 2

np.int64(2)

### Inverse of a matrix

In [76]:
w = np.array([[2, 5, 2], [1, 4, 3], [7, 2, 5]])
w

array([[2, 5, 2],
       [1, 4, 3],
       [7, 2, 5]])

In [77]:
np.linalg.inv(w)

array([[ 0.25      , -0.375     ,  0.125     ],
       [ 0.28571429, -0.07142857, -0.07142857],
       [-0.46428571,  0.55357143,  0.05357143]])

### Eigen values and eigen vectors

In [78]:
np.linalg.eig(w)

EigResult(eigenvalues=array([10.26502048+0.j        ,  0.36748976+2.30659304j,
        0.36748976-2.30659304j]), eigenvectors=array([[-0.45479072+0.j        ,  0.39955094-0.32717447j,
         0.39955094+0.32717447j],
       [-0.44264901+0.j        ,  0.31666053+0.29114342j,
         0.31666053-0.29114342j],
       [-0.7728048 +0.j        , -0.74045765+0.j        ,
        -0.74045765-0.j        ]]))

## Universal functions

- A universal function, or `ufunc`, is a function that performs element-wise operations on data in ndarrays
- These can be thought of as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results
- Most ufuncs are simple element-wise transformations, like `np.sqrt()` and `np.exp()`
- These are called unary `ufuncs` as they take only one array as an argument (an array) and perform calculation on every element of that array

Some unary universal functions (function that take a single array as argument):

| Function                                          | Description                                                                                                 |
|---------------------------------------------------|-------------------------------------------------------------------------------------------------------------|
| abs, fabs                                         | Compute the absolute value element-wise for integer, floating-point, or complex values                      |
| sqrt                                              | Compute the square root of each element (equivalent to arr ** 0.5)                                          |
| square                                            | Compute the square of each element (equivalent to arr ** 2)                                                 |
| exp                                               | Compute the exponent ex of each element                                                                     |
| log, log10, log2, log1p                           | Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively                           |
| sign                                              | Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)                                  |
| ceil                                              | Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)       |
| floor                                             | Compute the floor of each element (i.e., the largest integer less than or equal to each element)            |
| rint                                              | Round elements to the nearest integer, preserving the dtype                                                 |
| modf                                              | Return fractional and integral parts of array as separate arrays                                            |
| isnan                                             | Return Boolean array indicating whether each value is NaN (Not a Number)                                    |
| isfinite, isinf                                   | Return Boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively |
| cos, cosh, sin, sinh, tan, tanh                   | Regular and hyperbolic trigonometric functions                                                              |
| arccos, arccosh, arcsin, arcsinh, arctan, arctanh | Inverse trigonometric functions                                                                             |
| logical_not                                       | Compute truth value of not x element-wise (equivalent to ~arr)                                              |

In [79]:
arr = np.arange(10)
np.sqrt(arr).round(3)

array([0.   , 1.   , 1.414, 1.732, 2.   , 2.236, 2.449, 2.646, 2.828,
       3.   ])

In [80]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Some binary universal functions (functions that take two arrays as input):

| Function                                                   | Description                                                                                                  |
|------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------|
| add                                                        | Add corresponding elements in arrays                                                                         |
| subtract                                                   | Subtract elements in second array from first array                                                           |
| multiply                                                   | Multiply array elements                                                                                      |
| divide, floor_divide                                       | Divide or floor divide (truncating the remainder)                                                            |
| power                                                      | Raise elements in first array to powers indicated in second array                                            |
| maximum, fmax                                              | Element-wise maximum; fmax ignores NaN                                                                       |
| minimum, fmin                                              | Element-wise minimum; fmin ignores NaN                                                                       |
| mod                                                        | Element-wise modulus (remainder of division)                                                                 |
| copysign                                                   | Copy sign of values in second argument to values in first argument                                           |
| greater, greater_equal, less, less_equal, equal, not_equal | Perform element-wise comparison, yielding Boolean array (equivalent to infix operators >, >=, <, <=, ==, !=) |

In [81]:
v = np.array([0, 3, 2])

In [82]:
x

array([1, 2, 3])

In [83]:
np.maximum(x, v)

array([1, 3, 3])

In [84]:
np.power(x, v)

array([1, 8, 9])

## Statistical and mathematical functions/methods

A set of mathematical functions that compute statistics of the values of an entire array or using the data along an axis. These are accessible as methods of the `array` class.

Common statistical/mathematical function/methods:

| Method         | Description                                                                          |
|----------------|--------------------------------------------------------------------------------------|
| sum            | Sum of all the elements in the array or along an axis; zero-length arrays have sum 0 |
| mean           | Arithmetic mean; invalid (returns NaN) on zero-length arrays                         |
| std, var       | Standard deviation and variance, respectively                                        |
| min, max       | Minimum and maximum                                                                  |
| argmin, argmax | Indices of minimum and maximum elements, respectively                                |
| cumsum         | Cumulative sum of elements starting from 0                                           |
| cumprod        | Cumulative product of elements starting from 1                                       |

In [85]:
u

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [86]:
u.sum()

np.int64(5050)

In [87]:
np.sum(u)

np.int64(5050)

In [88]:
u.sum(axis = 0)    # sums each column "across the rows"

array([460, 470, 480, 490, 500, 510, 520, 530, 540, 550])

In [89]:
u.sum(axis = 1)    # sums each row "acroos the columns"

array([ 55, 155, 255, 355, 455, 555, 655, 755, 855, 955])

In [90]:
x

array([1, 2, 3])

In [91]:
x.cumsum()    # cumulative sum

array([1, 3, 6])

## Random number generation

In [92]:
# generate 10 values from the standard normal distribution
np.random.seed(1)    # setting the same seed ensures reproducibility
np.random.standard_normal(size = 10)    # output is 1D

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038])

In [93]:
np.random.seed(1)
np.random.standard_normal(size = (2, 5))    # output is 2D

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038]])

In [94]:
# generate 10 values from the normal distribution
np.random.seed(1)
np.random.normal(loc = 10, scale = 2, size = 10)    # mean = 10, sd = 2

array([13.24869073,  8.77648717,  8.9436565 ,  7.85406276, 11.73081526,
        5.39692261, 13.48962353,  8.4775862 , 10.63807819,  9.50125925])

### Creating a generator with a specified seed
Setting the seed each time can tedious. So, we can create a random number generator with a fixed seed

In [95]:
rng = np.random.default_rng(seed = 99)

In [96]:
rng.standard_normal(size = 10)

array([ 0.0824943 , -0.46441841,  0.05051506,  0.68623082, -1.75679051,
        1.6844316 , -0.45784284, -0.59642009, -1.04696756,  0.93179202])

In [97]:
rng.standard_normal(size = 10)    # same value as above since seed is the same

array([ 0.67498048,  1.2444412 ,  0.89308742,  0.26300494,  0.32851785,
        0.93524369, -0.87761299, -0.04589609,  0.38187174, -0.45253897])

Common methods under `numpy.random` and common distributions from which random numbers can be generated:

| Method          | Description                                                                  |
|-----------------|------------------------------------------------------------------------------|
| uniform         | Draw samples from a uniform distribution                                     |
| integers        | Draw random integers from a given low-to-high range                          |
| standard_normal | Draw samples from a normal distribution with mean 0 and standard deviation 1 |
| binomial        | Draw samples from a binomial distribution                                    |
| normal          | Draw samples from a normal (Gaussian) distribution                           |
| beta            | Draw samples from a beta distribution                                        |
| chisquare       | Draw samples from a chi-square distribution                                  |
| gamma           | Draw samples from a gamma distribution                                       |

## Concatenating arrays

In [98]:
y

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [99]:
w

array([[2, 5, 2],
       [1, 4, 3],
       [7, 2, 5]])

In [100]:
np.concatenate((y, w), axis = 1)    # axis = 1, concatenates side by side

array([[ 1,  2,  3,  2,  5,  2],
       [11, 12, 13,  1,  4,  3],
       [21, 22, 23,  7,  2,  5]])

In [101]:
# when axis is not mentioned, it set to 0 by defailt
np.concatenate((y, w))    # concatenates top to bottom

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [ 2,  5,  2],
       [ 1,  4,  3],
       [ 7,  2,  5]])

## Stacking arrays

In [102]:
stacked = np.stack((y, w))
stacked    # it treats the matrices y and w as slices of a 3D array

array([[[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23]],

       [[ 2,  5,  2],
        [ 1,  4,  3],
        [ 7,  2,  5]]])

In [103]:
stacked.shape

(2, 3, 3)

### `numpy.hstack()` and `numpy.vstack()`

In [104]:
np.hstack((y, w))    # same as concatenate with axis 1

array([[ 1,  2,  3,  2,  5,  2],
       [11, 12, 13,  1,  4,  3],
       [21, 22, 23,  7,  2,  5]])

In [105]:
np.vstack((y, w))    # same as concatenate with axis 0

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [ 2,  5,  2],
       [ 1,  4,  3],
       [ 7,  2,  5]])

## Spliting

https://numpy.org/doc/stable/reference/generated/numpy.split.html

`numpy.split(ary, indices_or_sections, axis=0)`

Split an array into multiple sub-arrays

Parameters:
- `ary`: an `ndarray`. an Array to be divided into sub-arrays
- `indices_or_sections`: int or 1-D array
  - If `indices_or_sections` is an integer, N, the array will be divided into N equal arrays along axis. If such a split is not possible, an error is raised.
  - If `indices_or_sections` is a 1-D array of sorted integers, the entries indicate where along axis the array is split. For example, `[2, 3]` would, for `axis=0`, result in:
    - `ary[:2]`
    - `ary[2:3]`
    - `ary[3:]`
  - If an index exceeds the dimension of the array along axis, an empty sub-array is returned correspondingly
- `axis`: `int`, optional. The axis along which to split, default is 0.

In [106]:
u

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [107]:
np.split(u, 10)    # assumes axis = 0

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40]]),
 array([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50]]),
 array([[51, 52, 53, 54, 55, 56, 57, 58, 59, 60]]),
 array([[61, 62, 63, 64, 65, 66, 67, 68, 69, 70]]),
 array([[71, 72, 73, 74, 75, 76, 77, 78, 79, 80]]),
 array([[81, 82, 83, 84, 85, 86, 87, 88, 89, 90]]),
 array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]

In [108]:
np.split(u, [2, 5])    # assumes axis = 0

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]]),
 array([[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]

In [109]:
np.split(u, [2, 5], axis = 1)

[array([[ 1,  2],
        [11, 12],
        [21, 22],
        [31, 32],
        [41, 42],
        [51, 52],
        [61, 62],
        [71, 72],
        [81, 82],
        [91, 92]]),
 array([[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25],
        [33, 34, 35],
        [43, 44, 45],
        [53, 54, 55],
        [63, 64, 65],
        [73, 74, 75],
        [83, 84, 85],
        [93, 94, 95]]),
 array([[  6,   7,   8,   9,  10],
        [ 16,  17,  18,  19,  20],
        [ 26,  27,  28,  29,  30],
        [ 36,  37,  38,  39,  40],
        [ 46,  47,  48,  49,  50],
        [ 56,  57,  58,  59,  60],
        [ 66,  67,  68,  69,  70],
        [ 76,  77,  78,  79,  80],
        [ 86,  87,  88,  89,  90],
        [ 96,  97,  98,  99, 100]])]